# -*- conf -*-

font=monospace:size=10
pad=2x0 center

# Rosé Pine
[cursor]
color=e0def4 555169
[colors]
background=191724
foreground=e0def4
regular0=403c58
regular1=ea6f91
regular2=9bced7
regular3=f1ca93
regular4=34738e
regular5=c3a5e6
regular6=eabbb9
regular7=faebd7
bright0=6f6e85
bright1=ea6f91
bright2=9bced7
bright3=f1ca93
bright4=34738e
bright5=c3a5e6
bright6=eabbb9
bright7=ffffff
