# -*- conf -*-

font=monospace:size=10
pad=2x0 center

[cursor]
color=000000 d1d1d1
[colors]
background=ffffff
foreground=000000
regular0=000000 # black
regular1=b30000 # red-aaa
regular2=006600 # green-aaa
regular3=f1ca93 # yellow-aaa
regular4=2e2eff # blue-aaa
regular5=9e009e # magenta-aaa
regular6=006161 # cyan-aaa
regular7=757575 # gray-aa
bright0=595959  # gray-aaa
bright1=eb0000  # red-aa
bright2=008a00  # green-aa
bright3=7a7a00  # yellow-aa
bright4=6161ff  # blue-aa
bright5=d100d1  # magenta-aa
bright6=008080  # cyan-aa
bright7=ffffff  # white
